### ISSUE TITLE
Implement data migration

### ISSUE THREAD

**Issue by husio** [iov-one/weave#1048]
As IOV I want to be able to write a data migration that will be executed exactly once in the future.

We are running `bnsd` on production, and we can no longer rely on the genesis to initialize state. 
Migration is not a problem when we migrate an existing data, because we can use [`migration` package](https://github.com/iov-one/weave/blob/master/migration/doc.go). 
Migration is currently impossible when a new functionality is introduced, or we wish to create or delete data. This is not possible with the existing `migration` package.

A proposed solution is to implement a new module where we define state modification. Execution of defined state modifications is triggered by a message.

Here is my earlier proof of concept implementation: https://github.com/iov-one/weave/commit/42f966e2213fc0dc244edce31152980728cd53fa
Data migration is defined as a Go function in the application that can access database 

https://github.com/iov-one/weave/blob/42f966e2213fc0dc244edce31152980728cd53fa/cmd/bnsd/x/statefix/statefixes.go#L7-L14

## Acceptance criteria
- [x] Data migration is a Go function, written as part of the application that execution cannot be altered or influenced from the outside,
- [x] Data migration can access database and change its state.
- [x] Each data migration can be executed only once. Execution of a state migration is stored on the blockchain, so that replying is possible,
- [ ] Anyone can request execution of a state migration,

**Comment by orkunkl** [comment]
Looks viable but I think we should put more thought in `Anyone can request execution of a state migration` clause and if it can possibly create a vulnerability and have a discussion here on that.

**Comment by webmaster128** [comment]
> Looks viable but I think we should put more thought in Anyone can request execution of a state migration clause and if it can possibly create a vulnerability and have a discussion here on that.

Ideally nobody had to trigger the migration manually and it would just be applied at a certain block height in the future. However, between two states there is a state transition and messages are used in Weave to trigger such a state transition. There are two possibilities to twigger the state transition via a message: (1) let the cron do it, (2) let a user do it.

I don't know about (1), maybe that makes sense. But (2) would work and is easy.

The migration code needs to ensure a some things:
1. It is either nilpotent (i.e. executing it multiple times leads to the same result as executing it once) or it can only be executed once
2. The execution must be independent of the transaction signer
3. It only works for a fixed chain ID
4. It only works starting from a fixed block height

With those limitations, I think it des not matter anymore, who sends the message, which is a very nice property because then we don't need to bother about authorization.
