### ISSUE TITLE
Question: why would I choose weave over cosmos-sdk?

### ISSUE THREAD

**Issue by damirka** [iov-one/weave#1070]
I've just discovered your project, and I'm curious about differences between weave and cosmos-sdk. I. know both are built on Tendermint (which is cool) so code/architecture designs look similar (check_tx, deliver_tx etc). 

- But what are the differences? 
- Why would I choose this project? 
- What was the initial reason to start weave? 
- Was it because of cosmos-sdk inability to do something?

**Comment by orkunkl** [comment]
In order to understand the difference between the projects, I recommend you to implement a small application(spike) project to see how the framework performs in terms of maintainability and simplicity. We believe Weave provides a much cleaner API interface and modularity. Weave designed to be composable by wrapping the modules together.
You can import [modules](https://github.com/iov-one/weave/tree/master/x) to your project piece by piece and develop yourself one. And I believe Weave [docs](https://docs.iov.one/docs/weave/welcome) are more comprehensive than Cosmos SDK. 

Benefits of Weave:
 - Better docs
 - On-chain migration mechanism(very important)
 - Modifiable authentication
 - Smaller modules
 - CRON jobs(AFAIK nonexistent in Cosmos. I might be wrong)
 - Modules do not depend on each other.
Cons:
 - If you are looking for a security model like Cosmos(dPOS), Weave does not provide one. We handle the security and rewards in `validators` module. On the other side, if you want to implement a novel security model and enjoy the Tendermint consensus engine, Weave is your go-to. It is impossible to detach the security model code in Cosmos as we are speaking since code is intertwined like a tarball.

**Comment by damirka** [comment]
Thank you very much for detailed explanation! Sorry for delay. I'm closing this issue.
