### ISSUE TITLE
Review permission system for NFT

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#108]
Builds on #103 - #107

At this point, you should have good experience with the requirements with a number of NFTs. Take the time to consider the permission (approval) system used in the original design and as implemented by the various use cases. There should be some room to abstract out common use cases and simplify the system, or add missing functionality to it...

Add thoughts for improvement during the course of previous issues, as this needs to be clarified from experience before pulling inot a sprint

**Comment by antoineherzog** [comment]
@ethanfrey Ideally, it would be great if NFT coud work with Atomic Swap. Not sure, if you want to do that during implementation phase or in a second phase.

**Comment by lehajam** [comment]
During my work on #148 I experimented a bit with the NFT approval system and I thought of a new implementation leveraging on the weave condition/authentication mechanism.
This approach has the following advantages : 
   - Make the nft approval system consistent with weave authentication mechanism, hence making things simpler
   - It is non intrusive and orthogonal to extensions thanks to weave
   - It's easy to handle special cases / new requirements / be modular by adding new authenticators or decorators, again thanks to weave

#### Below is a proposed workflow describing how this would work, please feel free to add comments and feedbacks 


  - Define an Approval struct containing the following data : 

```
message Approval {
    // the action this approval allows
    string action = 1;
    // number of times this approval can be used, unlimited = -1
    int64 count = 2;
    // block height timeout, no timeout = 0
    int64 timeout = 3;
    // the address for this approval eg. sig or multisig
    repeated bytes address = 4;
}
```   

  - Define a new tx allowing a list of approval IDs

```
type ApprovalTx interface {
	GetApprovals() [][]byte
}
```
 
 - Approval conditions are of the form : 

`approvals/action/approval_id` eg. `approvals/update/approval_id` 
 
 - Approval IDs are passed explicitly via the tx

 - There is a dedicated Decorator and an associated Authenticator to check approvals : 

```
Foreach approvalID Do 
     Load approval
     Check timeout
     Check context has sig / multisig
     If All Checks OK:  Add condition `approvals/approval.action/approval.id` to context
```

 - NFTs requiring approvals contain a list of approval conditions eg. 

```
message UsernameToken {
    bytes id = 1;
    bytes owner = 2;
    repeated bytes approvals = 3;
    repeated ChainAddress addresses = 4;
} 
```

 For example approvals could contain the following list: 
`[approvals/transfer/id_1, approvals/update/id_1, approvals/update/id_2]`

 - In the handler you check for your authorisation. For a particular handler you know what action you are performing eg. `update`. 
Therefore you can lookup the corresponding conditions from the nft (without loading the approvals) and check that you have one of the matching approval condition in the context. 

 - If no condition is available throw an unauthorized error

 - If there was a count on the approval, decrement it, if count equals 0 remove the condition from the NFT ?

 - Save NFT and approval back


#### Approval count management

Approval Count has to be managed by the extension because it is the only one to know when it has consumed it. 
It can feel a bit awkward having to manage the Approvals state from both Approval handler and the extensions using  them.
Rather than  having the Approval hold a count, we could make it part of the condition eg. `approval/update/approval_id:10` or  `approval/update/approval_id` for unlimited use.
It then becomes the (exclusive) responsibility of the extension to check it has a valid count, and to update it upon consumption. No need for a special `unlimited` value either.
Doing so only requires updating the condition within the NFT eg.  `approval/update/approval_id:10` becomes `approval/update/approval_id:9` and only the NFT is saved by the extension.
If count reaches 0 extension can decide to remove the approval or keep it. It can also handle routes to renew counts.

**Comment by alpe** [comment]
This is an interesting idea to extract the approvals from the base model. Thinking about this, I am wondering now how does the link from an incoming update message to a specific nft (type +id) work?  As I understand the approvals are loaded by Id in a first step:
> Foreach approvalID Do 

But coming from a [AddChainAddressMsg](https://github.com/iov-one/weave/blob/master/x/nft/username/codec.proto#L30) for example, you would have the NFT id only and not even the type available for a Decorator, right now. How would you find the approvals?

**Comment by lehajam** [comment]
I've implemented a small prototype to illustrate how the whole thing would work in the PR #179 
Main files to look at : 

 - [bnsd tests](https://github.com/iov-one/weave/pull/179/files#diff-004d3aa5d395ef2e8bf4e1f097d23a5dL78) to give you an overview of the full workflow (front to back)
 - [approvals context](https://github.com/iov-one/weave/pull/179/files#diff-00bf432767e3740204012d23966c982c) to see how approvals are managed
 - [username handler](https://github.com/iov-one/weave/pull/179/files#diff-38f64a4ef6d554646d86acbe96a4eeec) to see how approvals are used within an extension

Main highlights : 
 - It's based on weave conditions so its flexible and easy to integrate in clients
 - It works well with weave existing ecosystem eg. sigs multisig or even hashlock so you could have a one off secret based approval
 - It can be used with any extension outside of the scope of NFTs  

The way it works is as follow : 

 - Signers (sig or multisig) of a message produce a condition `approval/usage/address` so for pk address `64CEEA92BD744477D75E0348AF3BE06A3A7D8D59` you get `approval/usage/64CEEA92BD744477D75E0348AF3BE06A3A7D8D59`

 - NFTs request conditions of the form `approval/action/address:count:timeout` so to give update access to `64CEEA92BD744477D75E0348AF3BE06A3A7D8D59` NFT would hold the condition `approval/update/64CEEA92BD744477D75E0348AF3BE06A3A7D8D59` or for a limited access `approval/update/64CEEA92BD744477D75E0348AF3BE06A3A7D8D59:1:-1` (Count=1, Timeout=-1 eg. none)

 - The extension matches approvals using util functions in the approvals package so NFT condition  `approval/update/64CEEA92BD744477D75E0348AF3BE06A3A7D8D59` would be matched against `approval/usage/64CEEA92BD744477D75E0348AF3BE06A3A7D8D59` allowing `64CEEA92BD744477D75E0348AF3BE06A3A7D8D59` to proceed for updates

 - Util functions take care of updating approvals count when they're used

 - Approvals are fully part of the holder's state eg. NFT which is responsible for managing them. When saving the NFT you save the changes to the approval state, namely the count if any

 - Extensions must define routes to manage their approvals eg. adding/updating/removing approvals or no route for immutable. There is a handler to use in the approvals package, extensions define the message(s) they support and route them to a (local) instance of the approvals handler.  

 - Extensions also define the kind of approvals they support/require, the action is a string so it's very flexible, different extensions can use different actions and define new ones without impacting others

**Comment by ethanfrey** [comment]
Approvals need use-case. Kind of vestage now, also in https://github.com/iov-one/weave/tree/v0.9.3/x/nft

Let's make new clear issue (referencing this) when we have a focus (like account subkeys)
