### ISSUE TITLE
Allow registration of blockchains in genesis file

### ISSUE THREAD

**Issue by webmaster128** [iov-one/weave#184]
For CI tests in IOV-Core, it would be good if we could pre-register some blockchains in [genesis_app_state.json](https://github.com/iov-one/iov-core/blob/v0.8.1/scripts/bnsd/genesis_app_state.json). This allows us to test username registration without depending on blockchain registration transactions, making tests faster, more stable and easier to read.

**Comment by webmaster128** [comment]
Same for usernames

**Comment by ruseinov** [comment]
I'm going to work on some configuration constants import and it might give a good base for these too.

**Comment by husio** [comment]
I will give it a try :crossed_fingers:

**Comment by husio** [comment]
I am trying to figure out how to add blockchain creation from genesis file and it is a bit of a puzzle. Genesis is loaded by the `Initializer` and each extension can provide one i.e. `cash.Initialize`.
It makes sense to put blockchain genesis loading into `x/nft/blockchain`, because that's where the blockchain is defined.

The problem is that an application [can define only one initializer](https://github.com/iov-one/weave/blob/master/app/store.go#L38) and `bnsd` is already using `namecoin.Initializer`. Is one initializer limitation on purpose, so that an application cannot use more than one extension at a time? Or something like `MultiInitializer` should be added to bypass current limitation?

**Comment by ruseinov** [comment]
I'm working on a similar thing here: https://github.com/iov-one/weave/pull/188#discussion_r235084590 , so when this is done we should have a more or less generic way of propagating genesis configs to our extensions.

**Comment by ethanfrey** [comment]
> Is one initializer limitation on purpose, so that an application cannot use more than one extension at a time? Or something like MultiInitializer should be added to bypass current limitation?

Yes it was intended to chain them. There is a basic implementation that should work:
https://github.com/iov-one/weave/blob/master/app/genesis.go#L9-L12

**Comment by ruseinov** [comment]
@husio actually, disregard this. It looks like you could do with initializer instead, so you can move forward with that and I will look into my issue separately.
