### ISSUE TITLE
NFT: Consistent naming for blockchain id reference

### ISSUE THREAD

**Issue by ruseinov** [iov-one/weave#192]
Rename produbuf message attributes
```
AddChainAddressMsg.id -> AddChainAddressMsg.usernameId (the ID of the username NFT)
AddChainAddressMsg.chainID -> AddChainAddressMsg.blockchainId (the ID of the blockchain NFT)
```

https://github.com/iov-one/weave/blob/master/x/nft/username/codec.proto#L32
https://github.com/iov-one/weave/blob/master/x/nft/username/codec.proto#L39

---
We have this naming where a chain has an id and a `chainID` is used in tokenDetails
Yet, when we send AddChainAddressMsg chainID there is the actual id (PK)
Naming should be consistent when referring to a PK.

Example:
```proto
message AddChainAddressMsg {
    bytes id = 1;
    bytes chainID = 2;
    bytes address = 3;
}
```
https://github.com/iov-one/weave/blob/master/x/nft/username/codec.proto#L32
https://github.com/iov-one/weave/blob/master/x/nft/username/codec.proto#L39

**Comment by webmaster128** [comment]
In the client, [I now created](https://github.com/iov-one/iov-core/pull/535/commits/f1aa56291987bd3ce62c09df146ba56f99a60a42) two distict types:

* `BnsBlockchainId` is a binary identifier for the blockchain NFT in the BNS. What content is in there is undefined for now
* `ChainId` is the network identifier string generated by the genesis file

**Comment by ethanfrey** [comment]
There are two answer... what we can have ready and deployed in the next week, so we can use in the first iteration of the wallet (breaking changes later okay), and what we want *eventually*

For now, I think the fact that all lookups and references use the natural chainId, and it must be unique, that it makes sense to keep this as a pk. We could add a auto-generated pk, but then we either:

* use it everywhere to identify the chain make it very user-unfriendly to attach an address and query (no joins in the tendermint queries)
* or we use the chainId everywhere, add a unique secondary index for it, and treat it as a unique primary identification... or basically a second pk

In postgresql land, where we can do more complex things, the use as a separate field makes much more sense. Here... well, please convince me. I just see clients needing an extra query before forming a tx, and then also needing N queries after finding the user information in order to decipher the meaningless pks into the chainIds which we use client-side as a natural identifier

**Comment by ethanfrey** [comment]
After re-reading the original issue, I am a bit more confused:

```proto
message AddChainAddressMsg {
    bytes id = 1;
    bytes chainID = 2;
    bytes address = 3;
}
```

`id` is the `usernameId`
where `chainId` is the id of the referenced chain nft.

I wouldn't change the chainId part here, rather maybe make the name id more explicit.

**Comment by ruseinov** [comment]
@ethanfrey that gets more confusing when you look at the chain nft which has both id and chainID :)

**Comment by ethanfrey** [comment]
You mean this? https://github.com/iov-one/weave/blob/master/x/nft/blockchain/codec.proto#L19-L26

I don't see the problem there. There is no unqualified `id` field

**Comment by ethanfrey** [comment]
Or are you saying that `BlockchainNFT` inherits a `id` field from base.
https://github.com/iov-one/weave/blob/master/x/nft/blockchain/codec.proto#L9-L11

In this case, I am quite confused by the duplicate usage of chainId in `Chain`.

Especially since the test cases seem to use the `id` as the chainId string and never set/require the `chainId` field in `Chain`
https://github.com/iov-one/weave/blob/master/x/nft/blockchain/handler_test.go#L45-L48

**Comment by alpe** [comment]
The term `chainID` in blockchain details refers to the unique identifier of an external blockchain. This is what we have in tendermint genesis defined as chainID for example.

The `AddChainAddressMsg` must not use this term as this field points to an internal blockchain id instead. The blockchain details were added later that's why we have this confusing now, I guess. A better name would be `blockchainID` or `blockchainRefID`

**Comment by ethanfrey** [comment]
I thought these two were supposed to be the same thing...
Using the external unique identifier as blockchainRefId.

Anyway, happy for a productive conversation and example usages to refine this API. I just think we should somehow document the usages in general, not just minor changes, as these minor changes have consequences.

**Comment by webmaster128** [comment]
I think of this as different things that have the same content.

I think the question is: can we one and forever assume that the ChainID has the properties of a primary key:
* it will never change
* it is unique across the whole industry

Also: is the externally dictared format always suiteable for our software?

For tendermint this may be true. But when you look at Lisk and forks, the nethash is a hash of the genesis block, so a fork of the chain cannot simply re-assign a different value.

While I see that it is simple now, this ties things together that should probably be independent from a software architecture point of view. I'm afraid we don't understand the variety of external ChainIds good enough to use them as an immutable core part of our software.

**Comment by Isabello** [comment]
Some networks, like ethereum which have hard forked into ETC and ETH, share a `network_id` and use `chain_id` to differentiate transactions and to prevent replay.

I don't think we are the full way to implementing the object design found here: https://iov-one.github.io/bns-spec/_build/html/docs/data/ObjectDefinitions.html#blockchain-registration-tokens

There are some examples of full configurations there as well.

**Comment by webmaster128** [comment]
In the BNS spec it was now discussed that a NFT is destroyed when the bill is not paid and the username is free again. This is where you have two distinct NFTs that share the same username, making username as an ID problematic. A similar situation occurs for registrered expired blockchain registrations.

**Comment by ethanfrey** [comment]
> In the BNS spec it was now discussed that a NFT is destroyed when the bill is not paid and the username is free again. This is where you have two distinct NFTs that share the same username, making username as an ID problematic. A similar situation occurs for registrered expired blockchain registrations.

This is a very nice argument here. If we want to not re-assign keys when deleted and created, we need uuid. Of course DNS domains expire and can be reused....

If we do this, we need all references to be on the one-time uuid, and not using the publicly known chain_id or network_id

**Comment by webmaster128** [comment]
> If we want to not re-assign keys when deleted and created

I a history preserving system you most likely don't want to re-use the same ID. So yes, UUID for the win

**Comment by ruseinov** [comment]
It's nice to see that conversation here, but it'd be also nice to understand what is the conclusion here.
If we want to use uuid for our nft ids: let's rephrase the ticket and make it actionable. Right now it's a bit confusing, because the description of the ticket does not really match what we came up with.

**Comment by webmaster128** [comment]
@ruseinov who is supposed to make decisions in this repo?

If someone decides we separate the NFT ID and the chain ID, I have the following actionable items in mind:
* change NFT IDs to strings
* decide if client or backend assigns the NFT id and adapt the issue token messages accordingly, including the description in the protobuf files
* decide on an ID format and document in the protobuf files
* make it possible to query all blockchains for the client
* shedule for a breaking release

**Comment by ruseinov** [comment]
@webmaster128 This looks more like it. I suppose any one of use can take decisions when there is a valid proposal.

I will modify the ticket to reflect your thoughts.

About who assigns nft ids - if it makes things simpler on the client - you can assign there, if not - I don’t mind doing it via backend.

**Comment by alpe** [comment]
This issue was about fixing the `chainID` name in `AddChainAddressMsg`. 
The discussions about **uuid** vs **natural key** are important but should go into a separate ticket. In previous discussions we agreed already it was not about `if` we should do it but `when`.

**Comment by alpe** [comment]
I have opened https://github.com/iov-one/weave/issues/209 for the discussions now.

**Comment by webmaster128** [comment]
okay. Hard to talk about naming when it is not cleat what content belongs in there.

I read the original ticket again and in this ver case, I think
* `AddChainAddressMsg.id` -> `AddChainAddressMsg.usernameId` (the ID of the username NFT)
* `AddChainAddressMsg.chainID` -> `AddChainAddressMsg.blockchainId` (the ID of the blockchain NFT)
would help clarifying what this message does without changing the content of the IDs.

**Comment by alpe** [comment]
> AddChainAddressMsg.id -> AddChainAddressMsg.usernameId (the ID of the username NFT)
> AddChainAddressMsg.chainID -> AddChainAddressMsg.blockchainId (the ID of the blockchain NFT)
That are the correct references. 👍
