### ISSUE TITLE
username.ChainAddress: convert `address` field to string

### ISSUE THREAD

**Issue by webmaster128** [iov-one/weave#195]
Addresses are represented as strings in the client, allowing the user to have different string representations for the same binary address.

In Bitcoin for example there are [multiple address formats in use](https://en.bitcoin.it/wiki/Address) and we should respect the user's choice which one is used.

When we decode a Bench32 address into binary, we loose information (the prefix).

This allows the user to register address formats that we cannot decode into binary leading to a nice separation of concerns.

**Comment by ethanfrey** [comment]
Yes, I agree this should be a string.
When using this, there are a number of fields that are `[]byte`, but where we only expect/allow utf8/ascii `string` values, maybe nicer to work with by changing types

**Comment by husio** [comment]
I would like to work on this, but the change as I understand it is huge, so I would like to make sure I got this right first.

This change is about changing `Address` type from `[]byte` to `string` in [`username` package](https://github.com/iov-one/weave/blob/master/x/nft/username/codec.proto#L20).
In addition, [`nft` package must be updated](https://github.com/iov-one/weave/blob/master/x/nft/codec.proto#L20).

This gets quite deep, because at some point it is touching [`weave.Address`](https://github.com/iov-one/weave/blob/master/conditions.go#L80) which must be `[]byte`.

If this change is only about underlying type, then I think it's easier to keep it `[]byte`. Maybe the only change should be to not decode received representation, but rather convert it to `[]byte` as is?

**Comment by webmaster128** [comment]
The question is why an address that a user stores in the BNS is connected to weave.Address, which is made for [some specific kind of address](https://github.com/iov-one/weave/blob/master/conditions.go#L118)

**Comment by ruseinov** [comment]
I will look into converting `ChainAddress` to string in all the messages and the token itself

**Comment by alpe** [comment]
This `address` we are talking about is used in 3 places.
* https://github.com/iov-one/weave/blob/master/x/nft/username/codec.proto#L20
* https://github.com/iov-one/weave/blob/master/x/nft/username/codec.proto#L33
* https://github.com/iov-one/weave/blob/master/x/nft/username/codec.proto#L40

They are not limited to `weave.Address`

**Comment by ruseinov** [comment]
@alpe I’m aware of where it is used, it looks like an easy conversion
