### ISSUE TITLE
Rebase message numbers in protobuf

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#239]
Suggested by @ethanfrey:
> Maybe all the "middleware" info (fees, multisig, etc) should start at, say, 100 or 1000....

in:
```
cmd/bcpd/app/codec.proto
cmd/bnsd/app/codec.proto
```

**Comment by ethanfrey** [comment]
Yes, we should reserve a large space for all the different messages that can be in transactions (so ideally a add_username_nft can have the same number in all supporting chains).

And then a smaller numeric space for "middleware".

This will be a breaking change in the binary format, but then allow more forward compatibility. I would propose doing this before hugnet is released.

**Comment by ethanfrey** [comment]
On reflection, I think there will be far fewer middlewares. Since numbers over 127 take an extra bytes, we should try to limit those a bit... Forcing all middleware in the 1000+ range would be sub-optimal in that regard.

I would propose reserving 1-50 (or so) for middleware (which we currently use 4-5), and 51-infinity for the different message types. The base 70 messages or so will also be encoded in one byte. Also, we usually use multiple middleware fields (sigs, fees, etc) in one tx, but only one message field.

**Comment by ethanfrey** [comment]
Same message should have same number of both apps (if present in both)

eg. SendMsg is 1 at both

**Comment by ethanfrey** [comment]
This makes it easier to use one client for both (we can revisit this later when we add more messages)
