### ISSUE TITLE
Automate benchmarks and record them

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#263]
Figure out a way to do this with reliable, reproduceable conditions (not dev machines and not VMs with unreliable cpu availability).

This needs to be recorded somewhere as well, so we can compare a PR to master. Ideally in github.

This needs a clear design for a first version, then it can be built and we can optimize it later.

Note: before doing anything, make sure we have a reliable place to run this. eg. run benchmarks multiple times on travis and ensure they are constant.

Going for approach on https://github.com/iov-one/weave/issues/263#issuecomment-469255729

**Comment by ruseinov** [comment]
will take a look at the plan for this

**Comment by ruseinov** [comment]
So I have taken a look at a bunch of solutions and it seems like benchmarking only makes sense if the app is being deployed somewhere and then benchmarked. 

- We need to provide infra for deployment and auto-deploy PR's for benchmarking: for that we'll need to also implement a queue, to make benchmarking sequential per PR rather than parallel, for performance degradation reasons. We should also take care of commits pushed into a PR further, cause that could result in very long queues. 
- We could use a reporting/benchmarking tool such as this: https://www.smartmeter.io

@iov-one/blockchain-team let's gather some more requirements for this one in terms which benchmarks we want to run and how. Since we don't have any benchmarks as of yet it would be nice to understand how we want to organise this first before tackling this issue further.

**Comment by ethanfrey** [comment]
Nice standard compare tool: [benchcmp](https://godoc.org/golang.org/x/tools/cmd/benchcmp) to compare two versions

Some ideas on how to capture or automate collection:
[Store it all in influx db](https://www.influxdata.com/blog/announcing-grade-a-tool-to-track-your-go-benchmarks-in-influxdb/)
[Run on AWS and store JSON to visualize](https://github.com/cockroachdb/benchviz)

**Comment by ruseinov** [comment]
@ethanfrey storage could be done via google cloud storage.
In terms of testing, since we are using go tooling - we can just spin up a docker container, run the benchmarks, compare and notify the github hook with content. 

We don't even need to store anything except benchmarks from latest master.

**Comment by ruseinov** [comment]
If this sounds like a nice plan - I can flesh it out in detail tomorrow

**Comment by ethanfrey** [comment]
Simple docker container idea sounds good.
Keeping all benchmarks from master would be nice, if we ever want historical visibility.
But yes, compare latest on PR branch against latest master. No need to keep more on branches.

If this could produce a simple, extensible open source tool it would be ideal. This seems a very good usecase and could find nothing to do it. Even a basic script could get some other devs interested.

**Comment by ruseinov** [comment]
perfect, let's get this into this or next sprint - I'm glad to look into it. 
I couldn't find any good tool either. Will put up a short plan soon

**Comment by ruseinov** [comment]
So here is the basic plan

- [ ] create a basic go cli tool to interface with the storage and github for posting the results
- [ ] create a docker image which will contain this tool along with benchcmp
- [ ] create a container out of that image that would mount the code, run benchmarks, use the tool to download latest master results, run benchcmp to compare it and report to github
- [ ] create another container that would run and post the results of benchmarks on master every time it's being pushed to

**Comment by kmw101** [comment]
Definition of Done
============

Can we define what metrics and how are we measuring?

**Comment by ruseinov** [comment]
@kmw101 @husio this is irrelevant to this ticket. All benchmarks are done via `go test -bench` as @ethanfrey suggested, this ticket is about automating the execution and posting it back to github.

**Comment by kmw101** [comment]
Definition of Done
=============
All automation results in the data being posted to Github.

**Comment by husio** [comment]
If we will stick to the standard go benchmarking tool (`go test -bench`) we only have to build infrastructure to run them and work with the output.
Those benchmarks will be for tracking code change influence on the performance. 

## Running benchmarks

Benchmarks must always run on the same hardware. If we do not want out tests to slow down (we do not!) I propose to configure an another CI to run only benchmarks or an another project on Travis.
Output of running a benchmark suit should be stored for further analysis which brings us to the next point.

## Storing and comparing benchmarks

After running a benchmark suit we must store the output. Result is a text file which will never be altered. It can be stored anywhere and publicly readable (`weave` is an opensource project). Because we use google cloud it make sense to use Google Appengine. My second choice, because of huge simplicity of the platform, would be Heroku.

To analyze benchmarks we can build a web server that will be able list all bencharks and to run [`benchcmp`](https://github.com/golang/tools/blob/master/cmd/benchcmp/benchcmp.go) on demand. Any two benchmarks should be comparable.

The UI could be similar to wikipedias history comparison. Select two versions, click _Compare_ button and retrieve a `benchcmp` reusult.
![2019-03-04-142537_736x239_scrot](https://user-images.githubusercontent.com/1517/53736646-99e76b00-3e8a-11e9-9b57-c3474ade1cfd.png)

**Comment by ethanfrey** [comment]
I like the separate project in Travis CI for ease of use.
And have it only run on master branch, eg. after a PR is merged in.

I also like uploading to some generic cloud storage system. Anything we can add a minimal-access api key to travis ci is great.

We could do that as a first step, to collect and store the data, and then see if the number stay relatively constant when we make PRs that do not affect those changes (meaning underlying systems have stable processing power).

For this part, a cli tool that grabs the public benchmark numbers and compares them is enough. That will satisfy this issue.

Step 2, displaying the data to a user can be done as a second PR, once the data from 1 has been validated. This needs a bit more thinking and designing. and can be done as a second issue.

**Comment by ethanfrey** [comment]
This approach is good for maintaining a history of benchmarks over time running on a standarzied systems (not one dev's laptop).

We should also consider how the work is done locally when developing a benchmark. Maybe the cli tool is useful for that. Or maybe we just document some steps. So I would (on my laptop), run the benchmarks on master and again on my branch and compare them. Then add another commit, run and see if it improved. If I can use local files at many points, this tool may help to locate where changes in performance occurred.

**Comment by husio** [comment]
I was running benchmarks twice, five iterations each time:
1. https://travis-ci.com/iov-one/weave/jobs/182736318
2. https://travis-ci.com/iov-one/weave/jobs/182724491

I have copied output of 7 of them and compared using `benchcmp`. First first result with every other result and then second result with every other. Here is the result - [comparison.txt](https://github.com/iov-one/weave/files/2937107/comparison.txt)

A few thinkgs worth noting
1. Some benchamarks are failing. They must be fixed.
2. Working benchmarks are very fine grained and some of them result in 50% difference between execution of the same code :scream: 
3. It takes 4min to run benchmarks (onec all benchmarks that we have, some are broken). This might be because of crazy `BenchmarkSendTx` parameters.

**Comment by ethanfrey** [comment]
Thank you for this first investigation. It is great to shine some light and get an idea of where we are.

Yes, we need to fix all the benchmarks we have.

Interesting that most benchmarks are quite consistent (within 5%) between runs.
`BenchmarkSendTx/100-100-2` seems to be an outlier for some reason.

I think they run it more and more times until the total execution time is long enough to draw reasonable conclusions.

The full suite is nice for checking how eg. blocksize affects timing. For a baseline, we should probably pick one or two of those BenchmarkSendTx, one NormalizeCoins, etc... Like a hand-selected list that we use to compare.

**Comment by husio** [comment]
I will take this as my Friday project :unicorn:

**Comment by husio** [comment]
Here is what I have come up with.

I have written a near to zero dependency web server that I am deploying to heroku.  

- repository https://github.com/iov-one/benchsrv - click around
- server http://benchsrv.herokuapp.com/ that is deploying from a mirror https://github.com/husio/benchsrv because I want to use heroku auto deploy
- upload of the benchmark is done via `curl` and does not even support authentication right now
 `curl 'https://benchsrv.herokuapp.com/upload/' --upload-file benchmark.txt`

**Comment by ethanfrey** [comment]
> upload of the benchmark is done via curl and does not even support authentication right now

:smile:  Love prototypes

**Comment by ethanfrey** [comment]
> server http://benchsrv.herokuapp.com/ that is deploying from a mirror https://github.com/husio/benchsrv because I want to use heroku auto deploy

What is the problem with autodeploy from https://github.com/iov-one/benchsrv ? Do I need to approve something as organization admin?

**Comment by ethanfrey** [comment]
I looked at http://benchsrv.herokuapp.com/

Like the simplicity and functionality. Can be used for any workflow.
One question... these benchmarks are doctored, right? As most are the same, except for one or two runs that have 10x speed difference

**Comment by husio** [comment]
> What is the problem with autodeploy from https://github.com/iov-one/benchsrv ? Do I need to approve something as organization admin?

**Comment by husio** [comment]
I have finished the last part which is to run the benchmarks on the CI.

It is not possible to create another "project" on travis for the same repository. Because we do not want to slow down our tests I have created a project on CircleCI https://circleci.com/gh/husio/workflows/weave/tree/master
Because of permissions, this project is running benchmarks for my fork of weave. Configuration is quite easy https://github.com/husio/weave/blob/master/.circleci/config.yml

Benchmarks are gathered and can be browsed on http://benchsrv.herokuapp.com/

Everything is running on free tier right now and can be easily ported to another platform :muscle:

**Comment by ethanfrey** [comment]
Nice progress. :tada: :rocket: 

Starting to look like something we can use.

One quick observation is that the benchmarks have a sequence number and date, but no reference to the git commit or branch they came from. I think this minor change would make a huge utility improvement (maybe you can add this metadata when you push the file with curl?)

I like this initiative very much to provide us some realistic data we can use to validate theories and designs on how to make a more refined tool.

**Comment by husio** [comment]
I have added the commit information http://benchsrv.herokuapp.com/

**Comment by ethanfrey** [comment]
Nice fixup. Let's discuss future steps this next week.

**Comment by husio** [comment]
I will move this issue to `Done` without any further steps. The proof of concept is out there. I think we can pick this topic up once more when we will have benchmarks ready.
