### ISSUE TITLE
Better define anti-spam fee handling... who sets it, etc.

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#265]
We now have a good fee system. The only part missing in my opinion is the design for each individual validator to *subjectively* raise the CheckTx fee threshold in response to a flood of spam transactions. (Suggested by @alpe from his cosmos/GoS experience).

Since we now have RequiredFee enforced, we just need a Decorator that reads a threshold value from local data sets a given required fee in the CheckTx result (if it is not higher already with product fees), while DeliverTx is just a pass-through

We can pass this into any weave app (eg. bnsd) via a command-line flag or environmental variable

- [x] Create and test decorator. Takes a anti-spam fee in the constructor, and on response of CheckTx, it will update res.RequiredFee to `max(decorator fee, current res fee)`. It will pass through on DeliverTx
- [x] Add a flag to commands/server/start to parse this anti-spam fee from the cli. Either as a `Coin` or `*Coin`. Input should be `Validate`d there
- [x] Add nice parsing/display logic for Coin to and from a human readable format (eg `1.23IOV` rather than `{Whole: 1, Fractional: 230000000, Ticker: "IOV"}`) and use this for the command line parsing.
- [x] Pass this fee from the start command into the `AppGenerator`. We could add another argument, but we can do this cleaner. Besides home and logger, maybe make an "options" struct that we can add ever-increasing options to
- [x] Add this to `bnsd`. New arguments into `bnsd/apps.GenerateApp` passed into Stack. Stack/Chain should add the new `DynamicAntiSpamDecorator` below the `DynamicFeeDecorator` if passed in a non-zero cli option

Bonus (follow-up pr/story):
- [x] add QueryHandler to display the current value (zero or positive). Cannot use Bucket as this data is never stored on chain, have to implement QueryHandler for one defined path/key to expose in-memory value 

TODO: follow up issue to dynamically update checktx threshold without restart.

**Comment by ethanfrey** [comment]
We now have a good fee system. The only part missing in my opinion is the design for each individual validator to *subjectively* raise the CheckTx fee threshold in response to a flood of spam transactions. (Suggested by @alpe from his cosmos/GoS experience).

Since we now have RequiredFee enforced, we just need a Decorator that reads a threshold value from local data sets a given required fee in the CheckTx result (if it is not higher already with product fees), while DeliverTx is just a pass-through

Big question is how to set this info on the node:
* cli arg? 
* env var?
* message to unix socket/ http port??

Big question is "do we update a running process or can we restart it to reload the threshold???"

**Comment by alpe** [comment]
In gaiad is a `--minimum-gas-prices` CLI parameter and also an option to set it in the `gaiad.toml`. First option requires a restart. For the second I don't know if there is a watchdog to apply changes...
For a sentry node a restart could be acceptable but we should aim for a solution that does not require this.

**Comment by ethanfrey** [comment]
So, I can make one story with this as cli, then we work to design another way to update dynamically?

**Comment by ruseinov** [comment]
I took a brief look at this today and had a  couple of questions:
1. Since we are only dealing with prices/fees in IOV - why don't we simplify the cli param to be just `1.2345`, treat as string, split by `.` and assemble an iov coin?
2. Is there real need to have 2 decorators for this instead of embedding into FeeDecorator?
It does seem cleaner in terms of separation of concerns, but it also seems logical that FeeDecorator will always be there along with DynamicFeeDecorator. In which case sacrificing a bit of separation of concerns, that's not really needed in this case, we will have a bit less decorators to call which will result in better performance and possibly clearer definition of how fees work. 

I guess what I'm getting at is I think it is better to enhance what we currently have, cause we can always refactor that out later if it's ever needed. So in this case we can go for less extra code to write/maintain and also get a bit of a performance benefit and some clarity in terms of fee setup.

Also, since we need to supply an optional flag to enable AntiSpam fee threshold and configure actual fees in order to enable fees - while having 1 decorator we will stay fully flexible anyway.

**Comment by ethanfrey** [comment]
> Since we are only dealing with prices/fees in IOV - why don't we simplify the cli param to be just 1.2345, treat as string, split by . and assemble an iov coin?

Yeah, there is a fixed fee token but it is not always `IOV` on every chain. Splitting off letters at the end, with a decimal number in the front is not hard

> Is there real need to have 2 decorators for this instead of embedding into DynamicFeeDecorator?

As is, probably not so much reason, but this is really MvP, and there is a request for dynamically updating on a running process. When we extend that, or change how we configure it (use cli flags), etc. I feel it is nicer to leave that our, so people can also add custom logic for updating the values.

Re: Performance, that is a good question, the decorator as no-op is basically two function calls, which seem to cost around [2 ns/function call](https://billglover.me/2018/09/17/how-expensive-is-a-go-function-call/). Thus, I would not avoid them unless profiling shows that to be an issue.
