### ISSUE TITLE
Benchmark gconf Get

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#360]
Inspired by [PR review](https://github.com/iov-one/weave/pull/359#discussion_r260681500)

These are static values that can be loaded one when a chain starts, and never need to read from disk again. Some sort of caching could be good.

However, reflecting on current implementation, we do read from store and parse each time, but the read is actually buffered in a in-memory btree.

Since performance only really matter when there are 100+ tx/block, maybe this overhead is not too bad. Although keeping it in memory for the life of the chain is faster, maybe it is an unneeded optimization.

Please benchmark the following to decide whether to optimize:

* Create a level-db backed store
* Initialize with gconf for multiple values
* Benchmarks take two parameters:
  * type of data to load (int, Coin, string)
  * blocksize (# reads per cache)
* For each benchmark:
  * for each set of blocksize runs:
    * CacheWrap() the base store
    * Get the data (N times)
    * Discard the CacheWrap()

We should see the i/o overhead dominate with blocksize 1 and it is interesting to see the average time go down with 1, 10, 100, 1000 calls per cache. 

After benchmarks follow up on https://github.com/iov-one/weave/issues/361

**Comment by husio** [comment]
@ethanfrey please have a look at this commit https://github.com/iov-one/weave/commit/258d039378fbcb582a28ca5243cd87f4d04c09f5

I have implemented there a [nasty global cache](https://github.com/iov-one/weave/commit/258d039378fbcb582a28ca5243cd87f4d04c09f5#diff-741931f59b3629b60794fc4770119adfR27) :rage4: and provided benchmarks information for before/after results. I am benchmarking only `Int` and `Coin` functions. Integer because it is a primitive type and Coin because it is a complex structure. I think together they represent both the easiest and hardest cases.

**Comment by ethanfrey** [comment]
@husio My takeaway from this, is that we would save on the order of 3-5 microseconds per function call that passes through the fee handler. If gconf is used a few other places, we may end up with max 10 microsecond overhead per transaction. *max*

I think this is good to consider for now, and when we have proper benchmarks on other places, we can see if this makes sense to optimize (eg. at 1 ms per tx, this is pointless, at 50-100 microseconds per tx, this becomes quite interesting).

**Comment by ethanfrey** [comment]
I would make this issue close and reference it from the follow-up (which will drop in priority)

**Comment by ethanfrey** [comment]
Good work collecting the info, updated #361 and dropped the priority there
