### ISSUE TITLE
Reorganize imports for test clients

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#412]
To make a query using a test client, we need app.ResultSet (protobuf) as well as orm.SliceIterator.

Since we don't want to import those packages from weavetest, let's move them. 

SliceIterator (and add a ReverseSliceIterator) into weavetest... Can be imported in orm Tests

ResultSet protobuf along with helpers to and from Models (plus any cleanup of that code) goes into top level weave.

Please check if these suggestions make sense, and feel free to place them somewhere else, but they should be accessible by weavetest.

**Comment by husio** [comment]
I think `SliceIterator` cannot be moved to `weavetest` because it is used in `./store/iavl/adapter.go`.

`weavetest` was created as a container for mostly mocks for the top level `weave` package. I think it is ok to not put all testing tools there. It is not part of the `weave` package so that we can use the same names.

I think it is better if each package provides an API that makes it easy to test. Sometimes this means providing a function or a structure that is useful only during tests. I think this is perfectly fine.
For example [`gconf.SetValue`](https://github.com/iov-one/weave/blob/master/gconf/genesis.go#L39) is for testing only and it is part of the public `gconf` API. [`conf.NewCoinp`](https://github.com/iov-one/weave/blob/master/coin/coin.go#L38) is another example of an API created strictly for tests.

**Comment by ethanfrey** [comment]
Sure.

Let's put this ReadOnlyKVStore adapter as QueryClient in app. 

The rest of the weave runner can go into the app package as well or app/apphelper or so

What do you think?

**Comment by ruseinov** [comment]
I was about to take this, but I'm not really sure what the actionable items of this are, as the original ticket description indeed does not seem actionable at all

**Comment by husio** [comment]
I think this is about removing `weavetest` package dependencies. 

While working on the benchmarks, we have created `weavetest.abci.go` containing a `WeaveRunner` that implements [`Iterator` method](https://github.com/iov-one/weave/blob/master/weavetest/abci.go#L257).
Another issues is that [`ResultSet`](https://github.com/iov-one/weave/blob/master/weavetest/results.proto#L5-L7) declaration was copied.

We want to avoid `weavetest` importing other packages. This is because otherwise imported package cannot use `weavetest` and because it is better if each package is written with testing in mind and provides testing utilities on it's own.
`weavetest` is supposed to be testing utilities for the top level `weave` package. If a testing utility is for example for the `weave/store` package then I think it should be defined there as well.

@ethanfrey Is this description acurate?

**Comment by ethanfrey** [comment]
Good summary piotr.

We discussed some ways to do it. 
We want to keep the code out of cmd/Bnsd but be used in the benchmarks without messing up imports
