### ISSUE TITLE
Consistent use of weight/power in the API

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#453]
**Is your feature request related to a problem? Please describe.**
In the [multisig](https://github.com/iov-one/weave/blob/master/x/multisig/codec.proto#L25) proto we use `power` and in [distribution](https://github.com/iov-one/weave/blob/master/x/distribution/codec.proto#L33) `weight`. 
Same with the types uint32 vs int32 and max values
Multisig power value is max 255, distribution max is (2^31 - 1 )/ 200 . 
And now we are going to have 2^16 -1 with governance participant weights.

**Describe the solution you'd like**
Define weight types (name, max value, protbuf type) so that they can be used in different modules for a consistent api.

**Comment by ethanfrey** [comment]
I think sharing code is fragile.

We should be consistent with the naming. And the types (int32 vs uint32). As far as it makes sense.

Anyone want to make a concrete refinement to this proposal.

**Comment by husio** [comment]
My proposal as for what changes to apply in context of this story:

- change type [`Weight`](https://github.com/iov-one/weave/blob/master/x/multisig/model.go#L22) to `int32`, update protbuf message
- change the attribute name from [`power` to `weight`](https://github.com/iov-one/weave/blob/master/x/multisig/codec.proto#L25)

I think type `Weight` should stay in the `x/multisig` and should not be shared (or replicated) because
- it has [a custom validation logic](https://github.com/iov-one/weave/blob/master/x/multisig/model.go#L24-L33) that may not make sense in other places. For example each implementation can have different min and max value.
- it is [added for clarity](https://github.com/iov-one/weave/blob/master/x/multisig/codec.proto#L30-L31) as other attributes represent the same type of value
- above clarity is not needed in `x/distribution` as there is [only one place](https://github.com/iov-one/weave/blob/master/x/distribution/codec.proto#L33) where `weight` is used.

**Comment by ethanfrey** [comment]
I agree with @husio
