### ISSUE TITLE
Add owner and update to electorate / election rules

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#458]
**Is your feature request related to a problem? Please describe.**

We need a way to update the electorate and the rules, but it should require high permissions. Ideally, we would need an election to update the electorate... But the first step just handles the edit part.

**Describe the solution you'd like**

- Add a field of owner/admin to the two structs (Address)
- Add an UpdateXxx Message that can modify the value if signed by the owner
- Ensure new values are also valid values (like Create)
- Cannot change election rules or electorate during the open proposal. (Think about limiting opening proposals as well)
- Test

**Describe alternatives you've considered**
Describe alternative solutions or workarounds you've considered. 

**Additional context**

**Comment by alpe** [comment]
> Cannot change election rules or electorate during the open proposal

This can be easily abused to prevent a modification by opening a random proposal blocking this. Instead we may want electorates and rules versioned and immutable.

> Add a field of owner/admin to the two structs

They may benefit from being NFT types so that we get a permission system from there.

**Comment by alpe** [comment]
I have skipped NFT implementation for simplicity. Blocking an electorate  update by an open proposal is still the issue with this impl. I have limited the start time to 7 days in the future. Together with the max voting period it can block the update for 5 weeks, now.

Instead of limiting the number of open proposals it would be easier to set some high fees on the creation so that this is not done easily.
The versioning spike I did on the model addresses the problem differently so that it can't be blocked like this for new proposals.

#### Another question is what we want to update and how:
The simple approach I have started with would be limited to `electors` by `UpdateElectorateMsg` and `voting_period_hours` + `threshold` by `UpdateElectionRuleMsg` with full replacement.
