### ISSUE TITLE
Allow multisigs to pay fees

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#563]
As [pointed out in the comments](https://github.com/iov-one/weave/issues/563#issuecomment-492222721) this story is only about creating an Acceptance Test.

## Acceptance test
- [ ] create an acceptance test with `min_fee` set, `carl` having no tokens, but is part of a multisig `M`. Multisig `M` has tokens. `carl` is able to execute a transaction (eg. send) authorized by the multisig `M`, such that the multisig `M` pays the fees

---

**Is your feature request related to a problem? Please describe.**
If I want to use a multisig for my main account (eg. to allow multiple devices to access the same funds without copying mnemonics... also making it revokable), I cannot use it without each public key having enough money to pay fees.

There are big discussions in ethereum about "executable signed messages" for just this usecase, but I think we can enable this easily.

**Describe the solution you'd like**

- [ ] Change the Decorator Stack in bnsd (and bcpd) such that multisig is before fee collection
- [ ] AT with min_fee set, carl having no tokens, but part of multisig M. Multisig M has tokens. carl is able to execute a transaction (eg. send) authorized by the multisig, such that the multisig pays the fees
- [ ] Look at the interplay of multisig and fees decorators to ensure there is no vulnerability introduced by such changes

**Comment by ruseinov** [comment]
@ethanfrey I'm a bit puzzled about that one, I have checked it out and it seems like in bnsd we already have sig and multisig decorators upwards from all the fee decorators.

**Comment by ethanfrey** [comment]
As @ruseinov pointed out, the stack is correct. Maybe just one AT to resolve this.

Sorry not to check earlier, idea came up in a conversation and I was unsure how we set it up

**Comment by husio** [comment]
I think I have to change a lot in current acceptance tests in order to add multisig fee test. I will ask before putting a lot of effort into this. 

The current implementation is having [a big setup at the very beginning of all tests with quite some global variables](https://github.com/iov-one/weave/blob/master/cmd/bnsd/scenarios/main_test.go#L46-L97).
For my new tests, I have to change [the `MinFee` from zero to a non zero one](https://github.com/iov-one/weave/blob/master/cmd/bnsd/scenarios/main_test.go#L105).

I **must use a non zero fee** for my tests and I **cannot change it** for other tests. This is a conflict that cannot be solved with the current setup. Right now, all tests share the state and run one after another (in random order?) on the same tendermint/bnsd instance.

My proposal is to change this setup. Change [`TestMain`](https://github.com/iov-one/weave/blob/master/cmd/bnsd/scenarios/main_test.go#L59) to be a helper function called by each `TestXxx` function as initialization. Remove [global variables](https://github.com/iov-one/weave/blob/master/cmd/bnsd/scenarios/main_test.go#L47-L56) and return a big structure from the setup helper function with all the data that is global right now.
This means that when running locally, each test will run a fresh, independent `bnsd` instance.

A test may look like this after the change:

```go

func TestFoo(t *testing.T) {
   bnds, conf := setupBnsd(t, bsndMinimalFee("2 IOV"), bnsdChainID("foo"), optionFn3())
   defer bnsd.Close()

   // usual business...
}
```

The current setup is supposed to be executed on any `bnsd` instance (ie real network). I cannot enforce a configuration of minimal fee on it which makes the test useless. If I cannot enforce the setup, my test is invalid.

Is this scenario the right fit for our `scenarios` package or should it be written as a "unit test" instead?

**Comment by ruseinov** [comment]
I think the proposal to change TestMain is a fine approach. 

You could possibly hack your way through this, but it looks like this is not going to be faster or more productive than what you propose. 

This would also lay the groundwork for future tests.

**Comment by ethanfrey** [comment]
You could start and stop tendermint for a subset of tests. But it is quite a bit of overhead, and maybe doesn't play to well with tendermint's global variables (as you found out).

If this becomes too much pain without refactoring Acceptance Tests, please punt this issue (push it back to backlog). We need to oberhaul the ATs sometime, but doesn't need to be this week (unless you really want to)
