### ISSUE TITLE
Add schema and migrations to all extensions

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#564]
With #537 we have a framework to allow schemas and migrations for all extensions. But it is opt-in and no changes have been made to existing extension. We should enable this for all extensions (breaking change) and integrate with bnsd, updating ATs as needed.

After this breaking change, there should be a clean upgrade path on the server to upgrade or add extensions without a reset.

## Acceptance criteria

* All Handlers and Buckets using code from migrations.
* Update CHANGELOG
* Handle upgrades for Configuration objects... integration of Configuration with gconf

## Extensions to be updated 
- [x] ~`batch/`~ no change is required                                                                                                                                                 
- [x] `cash/`                                                                                                                                                  
- [x] `currency/`                                                                                                                                              
- [x] `distribution/`                                                                                                                                          
- [x] `escrow/`                                                                                                                                                
- [x] `gov/`                                                                                                                                                   
- [x] `hashlock/`                                                                                                                                              
- [x] `msgfee/`                                                                                                                                                
- [x] `multisig/`                                                                                                                                              
- [x] `namecoin/`                                                                                                                                              
- [x] `nft/`                                                                                                                                                   
- [x] `paychan/`                                                                                                                                               
- [x] `sigs/`                                                                                                                                                  
- [x] `utils/`                                                                                                                                                 
- [x] `validators/`  

## Further design decisions
- [ ] decide if we need transaction versioning https://github.com/iov-one/weave/issues/572
- [x] decide if the query interface should do automatic migration https://github.com/iov-one/weave/issues/579

**Comment by husio** [comment]
I thought I will start with the integration with `gconf` package. Unfortunately it is not possible because [`migration` is importing `gconf`](https://github.com/iov-one/weave/blob/master/migration/configuration.go). Unless those two are merged, I do not think there is a good way to use `migration` in `gconf`. I will leave this out for now.

**Comment by ruseinov** [comment]
@husio one thing we could do about that is extract gconf interfaces in to a separate (sub)package and use them instead of importing concrete implementation. But then you will need to pass the gconf instance in app-level somewhere, where it's initialised. 

It might actually be a good idea to have this abstracted out from the concrete implementation, but I can see how that complicates the user experience. 
One other thing that could be done is we have a global helper that returns instances of app-wide utilities via interfaces, then you can still do something like gconf.Load, but instead it would be utils.gconf.Load or something.

**Comment by husio** [comment]
@alpe I would like to close this issue as everything except `x/gov` is updated. Is that ok?

**Comment by alpe** [comment]
I will update gov after #581. Please let the issue open so that we don't forget about it.

**Comment by alpe** [comment]
all modules upgraded
