### ISSUE TITLE
Use `pkg_test` for testing

### ISSUE THREAD

**Issue by ruseinov** [iov-one/weave#578]
To further bulletproof our testing and enforce better modularity and testability of our code it would be nice to start using `pkg_test`. That prevents us, among other things,  from testing private methods and such, which ideally should lead to better design. 

This is what's used in stdlib and recommended by various Go professionals as well.

**Comment by husio** [comment]
I do not think this should be applied to all cases. It might make sense if you write example code so that you use package name prefix to document it better. I do not see how this helps with unit tests.
As a counter argument, you can no longer [use privately scoped code](https://github.com/iov-one/weave/blob/master/migration/orm_test.go#L17) and you API must be bigger.

What was frustrating for me and is alarming is when `pkg_test` was used to avoid [circular dependency](https://github.com/iov-one/weave/blob/master/x/nft/base/handler_test.go#L8) that test would otherwise introduce.

**Comment by ruseinov** [comment]
I'm not sure I fully agree on circular deps in tests, as test code should not affect dependency graph of actual packages, so it is actually nice to use a *_test package. It is, however, nice to avoid circular deps anyway. 

I don't really like the fact that tests pollute package namespace with their helpers and such.

Using *_test does lead to a slightly bigger public api, but it also forces you to design it in a way that is testable and nicely configurable, which is a plus, but a bit more work indeed.

**Comment by husio** [comment]
What I meat by circular dependency is that test is written the way that it cannot be part of the tested package. 
In the case of `x/nft` this is because test required `bnsd/x/nft/username` which requires `x/nft`. (there are more such cases in the code, this is the only one I could think of). Using `pkg_test` _enables_ introducing such imports, because code will compile and run.
An an example of a good design, we have `weavetest.Tx` that we use whenever a transaction is needed, instead of importing implementation from `bnsd`.

Code that is written in the `_test.go` file cannot be imported in the package. It is not part of the compilation process. It is not included in the package scope.

**Comment by ethanfrey** [comment]
I think it is preference.

There are cases where one over the other is definitely better, but for now, I would not make hard rules about it. If you wish to add a comment to our "soon to be created" knowledge base #726 you are more then welcome. Until then, closing the issue
