### ISSUE TITLE
Auto tagging on certain actions

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#596]
**Is your feature request related to a problem? Please describe.**
Highlight actions with tags

Follow up on:
https://github.com/iov-one/weave/pull/581#discussion_r281792037

**Describe the solution you'd like**
> Possibly auto-tagging with the msg.Path()

**Describe alternatives you've considered**
No doing anything.

**Additional context**
Cosmos-sdk uses certain [action tags](https://github.com/cosmos/cosmos-sdk/blob/master/x/gov/tags/tags.go)

**Comment by ruseinov** [comment]
Here it looks like we could indeed benefit from turning message paths into tags.

I would propose to implement a generic module that does this, which allows to map a certain `msg.Path()` with a name if needed.
This could be further extended to analyse returned `DeliverResult.Data` and tag that too, if mapping is specified. 

The second approach would be to create a convenient helper to add tags, so that we have something like 
```
type Tags []common.KVPair
func(t Tags) AddTag(key, value interface{}) error {
    check and convert types here as necessary
}
```
and also an auto tag with action, to avoid implementing that for every message.

**Comment by husio** [comment]
The referenced code seems to be gone. 

I like how it is done in https://github.com/iov-one/weave/pull/581#discussion_r281792037 because it is explicit. The full functionality is one place. You do not need to know the framework or conventions. Read the code line by line and you understand what is happening.

On the contrary, I do not like generic solutions. They might save typing at the cost of obfuscating executed operations.

I think it is OK to write repeatable, predictable and boring code :wink:

**Comment by ethanfrey** [comment]
This code is not for our use, but they clients. They need all handlers to tag in a very predictable way.

One solution is to manually do it... meaning add the following line to every deliver:

```go
res.Tags = []common.KVPair{
  {Key: []byte("action"), Value: []byte(msg.Path())},
}
```

The other is a decorator that does that line for your automatically.

**Comment by ethanfrey** [comment]
Add tags manually in every `Deliver` call

**Comment by ethanfrey** [comment]
Add tags automatically in a Decorator
