### ISSUE TITLE
Persist escrow/ aswap/ distribution address in model

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#644]
**Is your feature request related to a problem? Please describe.**

*Very useful to allow cosmos station to connect without using iov-core.*

The following modules generate addresses to store coins and transfer them based on their smart contract rules:
- [escrow ](https://github.com/iov-one/weave/blob/master/x/escrow/model.go#L102)
- [aswap ](https://github.com/iov-one/weave/blob/master/x/aswap/handler.go#L286-L288)
- [distribution](https://github.com/iov-one/weave/blob/master/x/distribution/model.go#L119-L123)
- gov (ElectionRule)
- multisig (Contract)
- paychan

The address calculation is in code only and not stored with the model data. This moves the complexity for recalculating the address to the client side to query a balance. Backend logic is replicated in the client (iov-core).
By storing the address within the model we also gain extra safety that no coins ever get locked due to changes in the address calculation rules.

**Describe the solution you'd like**
Store the generated address within the model so that it will be returned on queries. So that it can be used for querying the balance without further processing.

**Additional context**
iov-core can calculate addresses based on conditions.

Note that we need to have an ID before calculating an address. On creation, we only get the ID when Saving, so we would need to save twice, or add some callback to set Address in the model in a cleaner way.

We need to design the how - but at least they what and why are clear

**Comment by ethanfrey** [comment]
We need to find agreement on the approach we want to take to add this Address during creation (and not have the issue that Address depends on ID, which is only available *after* saving).

Once there is agreement on the general approach, this can go into "ready for development"

**Comment by ruseinov** [comment]
One good approach to take here is to generate a uuid and make a condition -> address out of it. 
This is a common practice for pre-generating ids to allow for idempotent message processing, but would also work here, cause our target is simple - we need some sort of random salt to append to preimageHash, base64 and an address from a condition.

**Comment by ethanfrey** [comment]
Do we want to do this?

**Comment by ruseinov** [comment]
I'll be happy to take this on, will sketch a proposal.

**Comment by husio** [comment]
Is this related to https://github.com/iov-one/weave/issues/712?

**Comment by alpe** [comment]
> Is this related to #712?

This issue is about storing a weave.address that holds tokens. But any impl can affect the other

**Comment by alpe** [comment]
- Simplest thing within handlers code only: do create then update
  ```go
	obj, err := h.bucket.Create(db, swap)
	if err != nil {
		return nil, err
	}
	swap.Address = SwapAddr(obj.Key(), swap)
	if err:= h.bucket.Save(db, obj); err!=nil{
		return nil, err
	}	
  ```

- Provide IDGenBucket.PeekNextID method to read the seq without incrementing it so that handlers can do peek + create

   ```go
	newID, err := h.bucket.PeekNextID()
	if err != nil {
	  return nil, err
	}
	swap.Address = SwapAddr(newID, swap) 
	obj, err := h.bucket.Create(db, swap)
	if err != nil {
		return nil, err
	}
   ```

- Pseudo random ID based on block information; problem when more then 1 create msg in a block -> check exists, incr, store

- A callback interface that receives the id and updates the model - pre-save
   ```go
     func (s *Swap)PreSave(key []byte)error{
	  s.Address = SwapAddr(key, swap) 
	  return nil
     }
   ```

**Comment by ruseinov** [comment]
@alpe I was leaning towards pseudo-random id, but the idea with Peek is even better, because of the sequential nature of blockchain execution.

I think it should be fairly easy to do and it will be a nice api.

Create and update is not as nice, mostly because you need to check errors on both..

`PreSave` hook is an okay idea too, but I personally prefer to avoid hooks absolutely necessary. 
Guess it's trauma from early development days with various web frameworks and forums :)

**Comment by husio** [comment]
If I remember correctly, during the refinement I have said that I do not understand this story and I trust you guys can take care of it. Here I am, trying to work on it :see_no_evil: 

I have checked all mentioned extensions (`paychan`, `distribution`, `escrow`, `aswap`, `gov`, `multisig`) and I do not understand what is expected in this story.
In [3 examples provided by @alpe](https://github.com/iov-one/weave/issues/644#issuecomment-510812791) there is an address assignment. I thought this is the address of the entity, so that when this entity is returned, we know how to reference it.
None of the mentioned extension entities is using an address as an ID. They all use raw `[]byte` that is a sequence value. A sequence value is not a valid weave address.

---

While implementing this change for the first extension (before realizing it does not make sense), I have learned that from [3 proposed solutions](https://github.com/iov-one/weave/issues/644#issuecomment-510812791) using create&update approach (1st one) is the easiest. Initially I was planning on adding `PeekNextID` and decided not to. This is because we have many bucket implementations and our [old `Bucket` interface](https://github.com/iov-one/weave/blob/master/orm/bucket.go#L33-L47) size is already beyond reasonable.

**Comment by ethanfrey** [comment]
The issue is that alpe, and now cosmos-station and the entire business dept, would like an easy way to find the address of an eg. multisig, so they can query the coins held by it. There is code to do so, in weave and iov-core, and it is not a very complex algorithm, but it is some "hidden knowledge" that would be easier for clients to make explicit.

Right now, eg multisig.Contract has an ID, which is good for DB lookups, but not for `cash.SendMsg`. The proposal is to add a field `bytes address = 5 [(gogoproto.cast_type=weave.Address)]` or such, that is set upon creation to the calculated address. As the swap address depends on the ID, this caused a chicken-and-egg problem, and the Peek proposal is a way to solve this.

Look at [SwapAddr](https://github.com/iov-one/weave/blob/0b3ba4b90d7d29e0887b8b293ee11110e73014ea/x/aswap/handler.go#L267-L271) to see what is discussed to be calculated and stored in the model upon create.

**Comment by ruseinov** [comment]
As discussed in Slack earlier I don't really think that `create and update` approach is a nice one, because in my opinion it's bad design and a hack.

If there are operations that need to know the id of the object before it gets saved to the database - we should expose a method to get the next sequence id.

**Comment by husio** [comment]
I have picked it up again, but I am not sure how to implement it. None of the proposed solutions seems to be good enough. I have described my findings in the pull request draft https://github.com/iov-one/weave/pull/891#issue-297579935
