### ISSUE TITLE
orm: make buckets chainable

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#645]
**Is your feature request related to a problem? Please describe.**
I like the new [ModelBucket](https://github.com/iov-one/weave/blob/master/orm/model_bucket.go#L33) but I can not use it with versioning.

**Describe the solution you'd like**
Within an adapter it could be possible to pass a VersioningBucket so that handlers can benefit from the simpler api of ModelBucket but also have access to the versioning features if required.

**Additional context**
Examples how we chain buckets already:
* [IDGenBucket](https://github.com/iov-one/weave/blob/master/orm/idgen_bucket.go#L14) enriches classic [Bucket](https://github.com/iov-one/weave/blob/master/orm/bucket.go#L33). 
* [VersioningBucket](https://github.com/iov-one/weave/blob/master/orm/versioning_bucket.go#L10) extends IDGenBucket

**Comment by husio** [comment]
I like the ability to be able to provide additional functionality on top of existing interface. I do not like how it is done in case of the `Bucket`. All `Bucket` extensions are using inheritance. I think a much better solution is creating a wrapper/middleware/decorator. 

Here is an example of both
```go
type baseBucket struct{}                                                        
                                                                                
func (b baseBucket) Hello() string {                                            
        return "hello base bucket"                                              
}                                                                               
                                                                                
type inheritingBucket struct {                                                  
        baseBucket                                                              
}                                                                               
                                                                                
type Bucket interface {                                                         
        Hello() string                                                          
}                                                                               
                                                                                
type wrappingBucket struct {                                                    
        b Bucket                                                                
}                                                                               
                                                                                
func (wb *wrappingBucket) Hello() string {                                      
        return "wrapping " + wb.b.Hello()                                       
} 
```

**Comment by ruseinov** [comment]
I like the idea of wrapping more too, as it also makes sure we don't embed objects with conflicting methods and such.

I guess a good idea is to have some sort of a combi-bucket that would satisfy all needed interfaces, but accept implementations as struct fields. 

The downside of this approach is that you need to implement the methods and call wrapped methods from within them. This could potentially get quite cumbersome, but since we don't need 100500 bucket wrappers - maybe a good tradeoff?

**Comment by ethanfrey** [comment]
The idea is great, these should be reusable and combinable.

Can you make a clear proposal of a new API that will perform this, particularly since ModelBucket exposes a different API that Bucket? I like @husio 's idea of making them private and only manually exposing these methods. They must implement the interface, that is all, we don't see the struct anymore.

I guess we have two interfaces... Bucket (which can be IDGen, Versioning, orm, migration....) and wrapped a few times... And ModelBucket (which is a top-level wrapper on top of any chain of wrappers, to provide a nicer interface).

Can we get a clear proposal by tomorrow's grooming so we can take this issue in. I think it would be quite good in order to finalize the various Bucket APIs soon.

**Comment by ruseinov** [comment]
Well, looking at the comments above and the general consensus, it would make sense to use something like this.

1. `ExampleBucket` that satisfies both `ModelBucket` and `Bucket` interfaces
2. A constructor that would take both of these implementations as parameters and assign them to private fields like so `func NewExampleBucket(bucket Bucket, modelBucket ModelBucket) ExampleBucket {
   return &exampleBucket{b: bucket, mb: modelBucket}
}
3. Expose underlying implementation's methods like this:
```
func(eb *exampleBucket) One(db weave.ReadOnlyKVStore, key []byte, dest Model) error {
   return eb.mb.One(db, key, dest) error
}
....
```

It would also make sense to choose a package where this is actually needed and implement a proposal that demonstrates the usage.

**Comment by ethanfrey** [comment]
Maybe the first step would be to decide if we like the ModelBucket interface as is, and if so, shall we make it the default public interface (no more direct importing Bucket)?

I would be happy to use this as an opt-in method for a bit to get more feedback from usage. Once we are happy, we can then replace Bucket with ModelBucket everywhere.

I don't like maintaining some joint API forever.

**Comment by kmw101** [comment]
Closing as API changes have been made and further API designs/discussion are in other issues.
