### ISSUE TITLE
Refactor Acceptance Test Harness

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#648]
They are hard to work with.
We need to make the ATs easier to use

TODO: please add feedback on how they can be easier to work with, write, maintain. Also some docs on their purpose and usage

**Comment by husio** [comment]
## Use functions and interfaces instead of structures and methods.

We use many _client_ implementations. I have recently introduced another one.
- https://github.com/iov-one/weave/blob/master/cmd/bnsd/client/client.go#L32
- https://github.com/iov-one/weave/blob/master/cmd/bnsd/scenarios/validator_test.go#L22

I think we should rethink our approach to accessing the _bnsd_ instance. We have many `Client` implementations which are confusing. I do not know which one to use, which one is _the_ client and why certain methods belong to certain implementations.

Rather than creating objects with methods, I think we should use functions and interfaces. For example [`bnsdtest.MustBroadcastTx](https://github.com/iov-one/weave/blob/master/cmd/bnsd/scenarios/bnsdtest/bnsdtest.go#L346-L349) is in my opinion [easier to read](https://github.com/iov-one/weave/blob/b7fc27a7ca51cf7dcf9b8412dc9ada04f68d8da4/cmd/bnsd/scenarios/gov_test.go#L97-L98) than [its counterpart](https://github.com/iov-one/weave/blob/b7fc27a7ca51cf7dcf9b8412dc9ada04f68d8da4/cmd/bnsd/scenarios/distribution_test.go#L44-L55).

The current implementation of `bnsdtest` helpers is using `EnvConf` which is another issue. A locally declared interface should be used instead.


## Write test helpers, not general functions.

With acceptance tests, we always test the happy path, which assumes all operations are successful. When using a general purpose API we must always check if the returned error is not nil and fail the test.

Instead of writing a [repetitive code](https://github.com/iov-one/weave/blob/b7fc27a7ca51cf7dcf9b8412dc9ada04f68d8da4/cmd/bnsd/scenarios/distribution_test.go#L44-L51) use a test helper that [handles error situation](https://github.com/iov-one/weave/blob/b7fc27a7ca51cf7dcf9b8412dc9ada04f68d8da4/cmd/bnsd/scenarios/bnsdtest/bnsdtest.go#L330-L332). This results in a [tidy test implementation](https://github.com/iov-one/weave/blob/b7fc27a7ca51cf7dcf9b8412dc9ada04f68d8da4/cmd/bnsd/scenarios/gov_test.go#L100-L111).


## Global state.

The current implementation relies heavily on [`EnvConf`](https://github.com/iov-one/weave/blob/b7fc27a7ca51cf7dcf9b8412dc9ada04f68d8da4/cmd/bnsd/scenarios/bnsdtest/env.go#L14-L34) which is a leftover from the global state. I think we would benefit if we apply two changes:
1. Remove global setup of certain functionality. For example [creation of contracts](https://github.com/iov-one/weave/blob/b7fc27a7ca51cf7dcf9b8412dc9ada04f68d8da4/cmd/bnsd/scenarios/bnsdtest/env.go#L28-L30). I think it is much better if each test must do it explicitly when needed as it is done with the [goverment tests](https://github.com/iov-one/weave/blob/b7fc27a7ca51cf7dcf9b8412dc9ada04f68d8da4/cmd/bnsd/scenarios/bnsdtest/env.go#L79-L84).
2. [Helper `bnsdtest` functions](https://github.com/iov-one/weave/blob/b7fc27a7ca51cf7dcf9b8412dc9ada04f68d8da4/cmd/bnsd/scenarios/bnsdtest/bnsdtest.go#L309-L365) must not take `EnvConf` as an argument but require directly what they need. When a client requires an interface instead of a precise type might be a good solution.


## Use small interfaces.

[The current implementation](https://github.com/iov-one/weave/blob/b7fc27a7ca51cf7dcf9b8412dc9ada04f68d8da4/cmd/bnsd/client/client.go#L31-L39) promotes big interfaces that are used everywhere and implemented by only one structure in the very same file.
I think it is better to:
- directly reference the structure type where needed. Using such an interface gives the wrong impression of avoiding tight coupling.
- declare interfaces in the package that they are used and **not** in the package that implements it.
- use interfaces with not more than 2-3 methods. This way providing another implementation or a wrapper is easy.


## Remote execution.

Acceptance tests are supposed to be working with local bnsd node created by the [`bnsdtest.StartBnsd`](https://github.com/iov-one/weave/blob/b7fc27a7ca51cf7dcf9b8412dc9ada04f68d8da4/cmd/bnsd/scenarios/bnsdtest/bnsdtest.go#L34) and when connected to a remote node.
The current implementation allows to [determine if we are using a local node](https://github.com/iov-one/weave/blob/b7fc27a7ca51cf7dcf9b8412dc9ada04f68d8da4/cmd/bnsd/scenarios/bnsdtest/env.go#L36-L39). This requires [providing separate paths](https://github.com/iov-one/weave/blob/b7fc27a7ca51cf7dcf9b8412dc9ada04f68d8da4/cmd/bnsd/scenarios/gov_test.go#L45-L48) depending on where we run the test.

The above is not perfect. We should write a single test and not worry about special cases and _ifs_ that must be added.

The above problem is hard to solve as we cannot control the remove environment setup. This means that test running remotely must never assume the initial state of a node. That, in my opinion, renders almost all of the remote acceptance testing impossible.
