### ISSUE TITLE
Some way to validate a genesis file

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#658]
**Is your feature request related to a problem? Please describe.**
There is no other way currently to validate a genesis file other than to setup a Tendermint + Bnsd. 

**Describe the solution you'd like**
A CLI parameter with the bnsd command would be great

**Describe alternatives you've considered**
* Hosted validation as a service where I can paste my genesis file into and get back any errors as list.
* Separate linter CLI tool

**Additional context**
This would benefit from mulitierr so that I can get a list of errors rather than a single one with each run

**Comment by ethanfrey** [comment]
I like the idea.

Something like `bnsd -home foo validate` that would return code 0 if genesis is valid and fail with useful error message if it is invalid?

This could be a generic command that pulls out the genesis file and runs the initializer on it:

https://github.com/iov-one/weave/blob/cb14bd433e40ecaba2df36be23f422bff7589f80/cmd/bnsd/app/init.go#L102-L112

https://github.com/iov-one/weave/blob/cb14bd433e40ecaba2df36be23f422bff7589f80/app/store.go#L320

**Comment by ruseinov** [comment]
Sounds good to me.

But what is a good approach here? Do we just want a generic high-level validation or do we want to reuse the init code of the app to determine which packages we have to register at startup for each app? That would look a bit different, because then we will need to share some code between app and this tool and also require each app to implement this.

I can see how properly structured it could bit an automagic process. 

There is another approach that could be taken, which is to have this method run tendermint + bnsd similar to ATs and throw errors. This could potentially reduce implementation time and also give us 100% overview of what is wrong about the current genesis, but then we lose the ability to return multiple errors, unless that is implemented on app level.

**Comment by ethanfrey** [comment]
> But what is a good approach here? Do we just want a generic high-level validation or do we want to reuse the init code of the app to determine which packages we have to register at startup for each app? That would look a bit different, because then we will need to share some code between app and this tool and also require each app to implement this.

I would like to use the result of `ChainInitializers`. You may have to manually pass this in, but then a command could parse a genesis file, extract the app_state, create an empty (in memory) kvstore, and run the initializers on that. If there is an error, print it, if not, it is good.

Having a separation Validate function runs the risk of the "validate init" and "execute init" functions returning errors on different cases. I see this something like a `--dry-run` flag, which may be another possibility for the cli

**Comment by alpe** [comment]
This should cover migration setup as well so that we can fail fast when a module is not setup proper.

**Comment by husio** [comment]
Closed in favour of https://github.com/iov-one/weave/issues/948
