### ISSUE TITLE
Add ID support for ModelBucket

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#712]
**Problem**:

When working with the ModelBucket, there were issues about returning the keys associated with the values. When I presented weave to a new dev (trying to onboard him with giving feedback on the tutorial), he was used to sql models and assumed the ID would be part of the model.

If we design ModelBucket for ease of use want to make a cleaner abstraction, I think we should store both Key and Value in the Model.

**Proposal**:

Add two methods to valid `Models`. `GetId() []byte` and `SetId([]byte) error`. It will now look like:

```go
type Model interface {
	weave.Persistent
	Validate() error
	Copy() CloneableData
	GetId() []byte
	SetId([]byte) error
}
```

One approach would just to define an `id` field in the protobuf to autogenerate the `GetId` method, and add a simple `SetId` method. When we save a model, we would do something like:

```go
key := model.GetID()
model.SetID(nil) // TODO: error handling
bucket.Put(db, key, model)
model.SetID(key)
```

On loading, we can also set ID.

**Comment by ethanfrey** [comment]
Note: let's do a spike on this.

**Comment by husio** [comment]
I understand this comes from an experience with the [active record pattern](https://en.wikipedia.org/wiki/Active_record_pattern) where each entity has an ID and can manage itself with an invisible database connection.

As always, I recommend trying every other solution before extending an interface. Big interfaces are in my opinion a sign of a bad API design.

Adding ID to the model makes you think that it is part of the model. This is required for the active record in order to be able to save itself. This is not true for how it is implemented right now in `weave`, where we use a [data mapper](https://en.wikipedia.org/wiki/Data_mapper_pattern) like approach.
Adding an ID to every stored entity would be an enormous change. If we do so, we must no longer accept a key as a separate argument to avoid missmatch between the ID attribute and the actual database key (database key is additionally prefixed).

The only method that would benefit from embeding an ID is [`Put` method](https://github.com/iov-one/weave/blob/master/orm/model_bucket.go#L57) of the `ModelBucket`. No other method would benefit from this change.

I cannot see a real benefit in this change. If you want to keep your model close to your key, you can always declare a tuple and use it.

```go
type KeyValue struct {
    Key []byte
    Value MyModel
}

kv := KeyValue{Key: someKey}
_ = b.One(db, kv.Key, &kv.Value)
_ = b.Put(db, kv.Key, kv.Value)
_ = b.Delete(db, kv.Key)
```
Even in this example I think it does not look very useful as only `Put` is using it.

**Comment by ethanfrey** [comment]
This was the original rationale behind the orm.Object structure, to group them... But it turned out to be a PITA to work with and everyone throws it away only to use the value part.

Adding the Key in the structure itself (not the serialzied part) is just a way to combine key and value into something people will not throw away.

Point about big interface is understood.

**Comment by ruseinov** [comment]
I would actually second the id inclusion into the model. We can also make it an embeddable protobuf type to unify if needed.

Reason for this is that we actually need to pass the ids along sometimes and lately more rather than less. Not having the id as part of the model is a huge pain in that regard. Same goes for working with relations.

I think we could benefit from this, given the store logic is wrapped into something that would seamlessly integrate with the new model design. The fact that the id is not a "part" of the model says nothing as neither it is in a relational store, where everything is it's own column and auto-increment integers are basically taking care of themselves. IMHO abstracting the model from the store is a good way forward for a nicer UX. 

I'd be happy to chip in a spike for some package with such an approach.

One point I agree on is that this is a big change, but it can be done gradually as we are still using the same store. I can see how gov package code could be improved by this.

**Comment by alpe** [comment]
I am with @husio on this. Coming from a document store you would not expect the ID in the data.    
Some concrete examples would help me to understand the use cases better.

> On loading, we can also set ID.

This would not create issues with proofs

**Comment by ruseinov** [comment]
> I am with @husio on this. Coming from a document store you would not expect the ID in the data.
> Some concrete examples would help me to understand the use cases better.

Well, MongoDB is a document store, so is couch and a bunch of others. ID is present in most of these, because it is convenient. 
I think the only real argument against having the id returned as part of the model is that it's a big change, but this can be done gradually where needed. 

> The only method that would benefit from embedding an ID is [`Put` method](https://github.com/iov-one/weave/blob/master/orm/model_bucket.go#L57) of the `ModelBucket`. No other method would benefit from this change.

There is more to it, sometimes the id is needed for assembling some sort of key or adding a relation.

**Comment by ethanfrey** [comment]
It is nice in the queries....
Anytime when the query is not by primary key (by secondary key, by prefix search, etc), you need to have {Key, Value} pairs.

This is what I did with `orm.SimpleObject`, which lead to all kind of nasty casting and helper functions and no one really liked.

Implementing `orm.Object` directly with the model, and passing that model in (so no type cast needed in the calling code) is basically what I wanted to do. The use of `GetID()` `SetID()` replaced `GetKey()`, `SetKey()` from `orm.Object`.

I am very happy for improvements in the design, but hope you understand the utility of the general approach and the problem it solves, so the alternative suggestion fixes the same problem (but cleaner).

**Comment by orkunkl** [comment]
Closed by https://github.com/iov-one/weave/pull/995
