### ISSUE TITLE
Define standard ModelBucket interface

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/weave#824]
**Is your feature request related to a problem? Please describe.**

Bucket was a nice and extensible idea... after some iterations both in weave and tutorial, I think we all find some form of ModelBucket easier to use. Let us define a canonical interface for ModelBucket, implement it (directly, not on top of Bucket), and then transition existing code to use it as the standard.

Some points I took away from eg. Alex's PR: https://github.com/iov-one/weave/pull/775

* BucketBuilder has a series of interfaces for nice *construction* of a Bucket, separate from *use* of a Bucket (eg. no more `.WithIndex()` on a Bucket, next to `.Get()`)
* Use standard CRUD naming - `Create`, `Update`, `Delete`. Separating Save into two cases helps enforce when we want to auto-gen an ID and when we can enforce the user to provide one

And from Piotr:

* Don't return interfaces that need to be laboriously cast. Accept the expected type from the user and fill it with data.

**Describe the solution you'd like**

I defined these types in tutorial, which I consider much nicer than current state, but far from perfect. I link them as a strawman: https://github.com/iov-one/tutorial/blob/master/morm/model_bucket.go#L16-L91

I guess I want to:
* Create a new items (auto-gen ID)
* Update an existing item
* Delete an item
* Read one or a range by primary key
* Read one or a range by secondary index

This proposes 4 different methods for reading, which could possibly be simplfied. 

I also store the ID inside the model struct, not when serialized, but when passing it around in memory. This is a big improvement in my eyes from `orm.Object`, which actually tried to do that in a very naive way:

```go
type Object interface {
	Keyed
	Copy() orm.CloneableData
	Validate() error
	Value() weave.Persistent
}
type Keyed interface {
	Key() []byte
	SetKey([]byte)
}
```

I currently use this as a Mode in tutorial... you see that the object itself is the Value. And `Key()/SetKey()` have been replaced by `GetID()/SetID()`:

```go
type Model interface {
	weave.Persistent
	Validate() error
	Copy() orm.CloneableData
	GetID() []byte
	SetID([]byte) error
}
```
I think the Copy() method can be removed if we don't use Bucket, but rather the more powerful ModelBucket reflection.

This is not a proposal for a final solution, but rather a number of features I was happy to have access to when writing Handlers and Controllers. I think we can clean this up and maybe enhance the functionality even more. (eg. pass in Context/BlockInfo as an argument to Save)

**Describe alternatives you've considered**

TODO: please add any good links here

**Comment by husio** [comment]
> BucketBuilder has a series of interfaces for nice construction of a Bucket, separate from use of a Bucket (eg. no more .WithIndex() on a Bucket, next to .Get())

I think it is much better to use functional parameters. Builders and factories are Java kingdom. Other than that, there is no functionality difference between those two approaches.
Even better than those two might be to implment wrappers that provide such functionality (discussed later). For example
```go
bucket := orm.WithIndex("thing-foo", thingFooIdx)
    orm.WithIndex("thing-bar", thingBarIdx,
    orm.NewBucket("things", &Thing{}),
))
```

Regardless, I think removing `WithIndex` and similar methods from the bucket is amazing! The smaller the interface, the happier the programmer! And more important, anything that mutates the state like that can cause trouble.

> Use standard CRUD naming - Create, Update, Delete. Separating Save into two cases helps enforce when we want to auto-gen an ID and when we can enforce the user to provide one

Separating the current `Put` into `Create` and `Update` does not in my opinion enforce auto generation of the ID. For me `Create` and `Update` have different assurances. I expect that `Create` will fail if an entity with a given ID already exists. Similarly `Update` must fail if the entity does not exist yet. `Put` does not care about any of those as it simply writes content to the database.

I am quite proud of how the current `Put` method is implemented. It is a single method that solves the problem of generating an ID and gives you the flexibility of providing an ID as well. It also allows you to update an entity. I would trade it for `Create` and `Update` only if we want the presence checks.

> I think the Copy() method can be removed if we don't use Bucket, but rather the more powerful ModelBucket reflection.

This is great as it makes a model implementation much easier. `Copy` is no longer needed as the destination structure is provided by the API user.
Remoing `Copy` will also be an optimization as all unnecessary allocations required by copying are removed.
Because the bucket no longer produce (returns) the model instances, it no longer requires model instance during the initialization. Bucket creation can therefore be simplified.
```go
OldBucket("things", &Thing{}) // The current implementation.
NewBucket("things") // The new implementation.
```

---

I think it is important to design the new API with composition in mind. It should be possible to use the new interface to build a [layered bucket](https://ichef.bbci.co.uk/news/660/media/images/80896000/jpg/_80896768_red-onion-think624.jpg). A few examples:
```go
plainBucket := orm.NewBucket("things", &Thing{})

migratableBucket := migrations.AutoMigrate("thinkgspkg", "things", orm.NewBucket("things", &Thing{}))

measuredBucket := prometheus.Measure("things-migratable",
    migrations.AutoMigrate("thinkgspkg", "things",
        prometheus.Measure("things-plain",  orm.NewBucket("things", &Thing{}))
    )
)
```
The above constructs can be simplified if we no longer require model instance during bucket creation. Additionally I think it might be good if bucket would have a `Name` attribute to aboid explicitely passing it to all wrappers. Applying those changes, the last two line would be

```go
migratableBucket := migrations.AutoMigrate("thinkgspkg", orm.NewBucket("things"))

measuredBucket := prometheus.Measure("things-migratable",
    migrations.AutoMigrate("thinkgspkg", 
        prometheus.Measure("things-plain",  orm.NewBucket("things"))
    )
)
```

While it is more code to implement each functionality separately, there are several adventages:
- implementations are truly independent
- implementations are chainable
- you can add and remove implementations without a chance of breaking existng code (maybe not when removing)
- you can test **easily** each implementation and the core functionality can be tested by a generic test case. Tests are simple as they have to prove only one functionality

**Comment by ethanfrey** [comment]
> I am quite proud of how the current Put method is implemented. It is a single method that solves the problem of generating an ID and gives you the flexibility of providing an ID as well. It also allows you to update an entity. I would trade it for Create and Update only if we want the presence checks.

I think those presence checks would be great, with clear errors (ErrAlreadyExists). We do those checks everywhere we create entities with non-autogenerated ids

**Comment by ethanfrey** [comment]
```
OldBucket("things", &Thing{}) // The current implementation.
NewBucket("things") // The new implementation.
```

> Additionally, I think it might be good if the bucket would have a Name attribute to avoid explicitly passing it to all wrappers.

Yes. Nice ideas

**Comment by ethanfrey** [comment]
Interesting example with prometheus.

I was thinking of removing much of the chaining logic, as we have a standard bucket and a migrations bucket and not 7 types. But, yeah, good to allow people to add wrappers like that. We also add wrappers around kvstore for recording which keys were touched.
