### ISSUE TITLE
Queries for bnscli tool

### ISSUE THREAD

**Issue by kmw101** [iov-one/weave#852]
There are a number of queries that are needed to help the governing board.

- [ ] ~Show all open proposals~ List all proposals
- [ ] ~Get the status of a proposal~ Show details of a proposal - input proposal id
- [ ] ~Show vote status - by proposal id~ this and the following are included in the proposal details

- Total votes
- Total  Yes votes
- Total No votes
- Total Abstain votes
- Quorum
- Threshold

- [ ] ~Show vote result by status - input status <passed, failed, aborted>~ result is in proposal details
- [ ] ~Members of a committee - input committee id, return committee ids~ show electorate details by version, id
- [ ] ~Show committees - return Committee id~ list all electorates

New:
- [ ] List all electorate versions for an id
- [ ] List all election rules
- [ ] List all versions for an election rule by id
- [ ] Show election rule details by id, version

**Comment by husio** [comment]
I gave it a try in https://github.com/iov-one/weave/tree/queries_for_bnscli_issue_852

**Comment by alpe** [comment]
This is what I was using for tests: https://github.com/iov-one/weave/pull/872

**Comment by husio** [comment]
I cannot make pull request because GitHub is rejecting code changes. This is how the tooling will allow for the required queries:

- list all proposals
  `./bnscli query -path "/proposals"`

- show single proposal with ID 321 
  `./bnscli query -path "/proposals" -data "321"`

- all votes for proposal with ID 321 
  `./bnscli query -path "/votes/proposals" -data "321"`

- list addresses that voted YES on proposal with ID 321 (1 == yes, 2 == no, 3 == abstain)
  `./bnscli query -path "/votes/proposals"  | jq -c '.[] | select(.Value.voted == 1) | .Value.elector.address'`

- list addresses that voted NO on proposal with ID 321 
  `./bnscli query -path "/votes/proposals" | jq -c '.[] | select(.Value.voted == 2) | .Value.elector.address'`

- count NO votes on proposal with ID 321 
  `./bnscli query -path "/votes/proposals"  | jq -c '.[] | select(.Value.voted == 2)' | wc -l` 

- list all electorates
  `./bnscli query -path "/electorates"`

- show an electorate with ID 222 and version 888 
  `./bnscli query -path "/electorates" -data "222/888"`

- list all election rules
  `./bnscli query -path "/electionrules"`

- list all version of an election with ID 222 
  `./bnscli query -path "/electionrules" -data "222"`

- show an election rule with ID 222 and version 888 
  `./bnscli query -path "/electionrules" -data "222/888"`

- list all version of an election rule with ID 222 
  `./bnscli query -path "/electionrules" -data "222"`


@kmw101 is this acceptable?

**Comment by kmw101** [comment]
It is indeed. Thank you.

**Comment by husio** [comment]
I have created a pull request. Some commands require [jq to be installled](https://stedolan.github.io/jq/).
