### ISSUE TITLE
VersionedIDRef serialization for db key must be deterministic

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#918]
## Expected Behavior
Serializing the same structure should return the same value for the binary representation that is used as key in VersioningBucket.

## Actual Behavior
Unfortunately this is not guaranteed: https://developers.google.com/protocol-buffers/docs/encoding#order

## Acceptance criteria
- [x] Big endian encoding is used to serialize the version number in the `orm.VersioningBucket`.
- [x] Serialized VersionedIDRef consists of a []byte array `[ n bytes ID ][ 4 bytes version ]`
- [x] bnscli works with the new encoding format to do range queries by id and precise id, version matches

While the ID is in current implementations a big endian serialized int64, there is no need to enforce the ID byte array to be exactly 8 bytes in the bucket.

**Comment by ethanfrey** [comment]
Hmmm... I usually used a fixed field, or a bigendian encoded int64 for the db key, which were quite deterministic.

Protobuf "non-determinism" should be clarified. The point is, there are multiple valid binary encodings that deserialize to the same structure. This would also be an issue for signature malliability or potentially fuzzing parsers - like overriding portions of a subfield later and maybe this is not displayed correctly before validating.

In any case, the solution for auth was to re-serialize the parsed structure with the gogoprotobuf protobuf encoder, which does produce a deterministic encoding (note there is codegen and no maps there). Actually, every single protobuf encoder I know of is deterministic. What is not guaranteed is that parsing and reserializing a given structure will produce the same result in all of them. The issue we have between js (iov-core) and go is with zero values - in js land `undefined` and `null` are no encoded, while zero-values are encoded. In go-land, there is no `undefined` or `null` for many fields, so they just skip encoding zero-values for ints and strings, which can caused failed signature checks. (And why iov-core explicitly coverts zero values of primative types to `null` for the protobuf objects).

I would be very curious how you can reproduce this in go. Is this just an inconsistency with iov-core, especially when one of the fields is 0? I would also consider a custom encoding with lexographical ordering here - meaning a prefix scan can quickly find the highest version, rather than parsing them all. Protobuf compresses all ints, so prefix scans are impossible (you need bigendian encoded fix-length integers).

As an aside, I did think to use `fixed64` protobuf encoding to get such ordering, but it uses little-endian encoding, so the byte-ordering is not consistent with the numeric-ordering.

```
Non-varint Numbers

Non-varint numeric types are simple – double and fixed64 have wire type 1, which tells the parser to expect a fixed 64-bit lump of data; similarly float and fixed32 have wire type 5, which tells it to expect 32 bits. In both cases the values are stored in little-endian byte order. 
```
https://developers.google.com/protocol-buffers/docs/encoding

**Comment by ethanfrey** [comment]
If you really want the deterministic encoding guaranteed in the spec, check out https://github.com/tendermint/go-amino

(There is almost a proper javascript codec for it now - https://github.com/node-a-team/ts-amino)

**Comment by webmaster128** [comment]
The implications for IOV-Core are probably much smaller than I initiall thought (https://github.com/iov-one/iov-core/issues/1182). However, it is a breaking change still and will require a new breaking IOV-Core and a new Testnet.

**Comment by ruseinov** [comment]
@alpe why in the acceptance criteria we are talking about `use big endian encoding to combine two unsigned int64 numbers` if the `[ 8 bytes ID ]` is not guaranteed to be a number in the current implementation and is not validated in any way.

I feel like this is missing some context. 

Shall we use amino instead to avoid this issue?

**Comment by alpe** [comment]
@ruseinov you are right that the id in the bucket api is []byte but in fact it is a serialized seq ([electorate](https://github.com/iov-one/weave/blob/master/x/gov/bucket.go#L22), [rules](https://github.com/iov-one/weave/blob/master/x/gov/bucket.go#L55]. I will update the acceptance criteria to use the already serialized sequence id with the to be serialized version number.
