### ISSUE TITLE
DDOS risks in HTTP router implementation

### ISSUE THREAD

**Issue by kmw101** [iov-one/weave#939]
From the Security Audit

> The HTTP router implementation uses a regular expression to parse the request string.
 
> A more performant option is to use a prefix tree to route requests, as per https://github.com/julienschmidt/httprouter (which is mentioned in the code comments).
 
> Regular Expressions potentially expose the application to computational denial of service via specially crafted inputs. This is also known as ReDoS, https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS .

**Comment by husio** [comment]
If I understand what this audit report is about then I am deeply disappointed by the lack of professionalism on their side. I truly hope I misunderstood what they meant. 

If their report is about [the `isPath` regular expression use](https://github.com/iov-one/weave/blob/master/app/router.go#L12), which is the only place that `julienschmidt/httprouter` is mentioned, then there is no risk. Regular expression is used only during the application initialization, when [the `Router.Handler` is called](https://github.com/iov-one/weave/blob/master/app/router.go#L37-L42). When handling a message, the lookup is done with O(1) complexity, because [we are using an index](https://github.com/iov-one/weave/blob/master/app/router.go#L53-L54).

Furthermore, if they bothered to check the first two paragraphs of the [Go documentation for the regexp package](https://golang.org/pkg/regexp/#pkg-overview), they would learn that 

>  The regexp implementation provided by this package is guaranteed to run in time linear in the size of the input. (This is a property not guaranteed by most open source implementations of regular expressions.) For more information about this property, see 

:disappointed:

**Comment by kmw101** [comment]
No action needed.
